05-31 18:12:38 root         INFO     Filter ID: None - processing all journals
05-31 18:12:38 root         INFO     GPT Processing: Disabled
05-31 18:12:46 root         INFO     Successfully clicked cookie consent button
05-31 18:12:51 root         INFO     HTML GATHERED
05-31 18:12:51 root         INFO     LINK GATHERED
05-31 18:12:51 root         INFO     /toc/aera/62/3
05-31 18:13:07 root         INFO     No cookie consent button found or needed
05-31 18:13:12 root         INFO     GPT disabled
05-31 18:13:12 root         INFO     LINK GATHERED
05-31 18:13:12 root         INFO     /toc/aera/62/2
05-31 18:13:27 root         INFO     No cookie consent button found or needed
05-31 18:13:32 root         INFO     GPT disabled
05-31 18:13:32 root         INFO     LINK GATHERED
05-31 18:13:32 root         INFO     /toc/aera/62/1
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107fcf690>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108448c50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108449610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10844af50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10844b150>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108449950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108448810>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10844bc10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108458790>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10845a150>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10845ad90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10845b950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108469350>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108469f90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10845bfd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108459e50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108458b10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084583d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1084481d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10844abd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108449490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108443c90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108468490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10846add0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108478550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108443a10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10844a050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/847665be-c1d8-4581-ada1-e405f18c7b5f/element
05-31 18:13:38 root         INFO     No cookie consent button found or needed
